{% set version = "4.0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggthemes
  version: {{ version|replace("-", "_") }}

source:
  fn: ggthemes_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggthemes_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggthemes/ggthemes_{{ version }}.tar.gz
  sha256: 0b71202b253cb85bc8d49b74ace2cf87f04f235e879eb2ef71ba8cb03938c578

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-assertthat
    - r-colorspace
    - r-ggplot2 >=2.2.0
    - r-scales

  run:
    - r-base
    - r-assertthat
    - r-colorspace
    - r-ggplot2 >=2.2.0
    - r-scales

test:
  commands:
    - $R -e "library('ggthemes')"  # [not win]
    - "\"%R%\" -e \"library('ggthemes')\""  # [win]

about:
  home: http://github.com/jrnold/ggthemes
  license: GPL-2
  summary: Some extra themes, geoms, and scales for 'ggplot2'. Provides 'ggplot2' themes and
    scales that replicate the look of plots by Edward Tufte, Stephen Few, 'Fivethirtyeight',
    'The Economist', 'Stata', 'Excel', and 'The Wall Street Journal', among others.
    Provides 'geoms' for Tufte's box plot and range frame.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
