{% set version = "5.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggthemes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggthemes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggthemes/ggthemes_{{ version }}.tar.gz
  sha256: 074819acfe8bb2233426a0fef3bb448c5ce817bb14d517252fa05932e28bbd0e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-purrr
    - r-scales
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-purrr
    - r-scales
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('ggthemes')"           # [not win]
    - "\"%R%\" -e \"library('ggthemes')\""  # [win]

about:
  home: http://github.com/jrnold/ggthemes
  license: GPL-2
  summary: Some extra themes, geoms, and scales for 'ggplot2'. Provides 'ggplot2' themes and scales that replicate the look of plots by Edward Tufte, Stephen Few, 'Fivethirtyeight', 'The Economist', 'Stata', 'Excel', and 'The Wall Street Journal', among others. Provides 'geoms' for Tufte's box plot and range frame.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggthemes
# Version: 4.1.1
# Title: Extra Themes, Scales and Geoms for 'ggplot2'
# Authors@R: c(person("Jeffrey B.", "Arnold", role = c("aut", "cre"), email = "jeffrey.arnold@gmail.com",  comment = "<https://orcid.org/0000-0001-9953-3904>"), person("Gergely", "Daroczi", role = "ctb"), person("Bo", "Werth", role = "ctb"), person("Brian", "Weitzner", role = "ctb"), person("Joshua", "Kunst", role = "ctb"), person("Baptise", "Auguie", role = "ctb"), person("Bob", "Rudis", role = "ctb"), person("Hadley", "Wickham", role = c("ctb"), comment = "Code from the ggplot2 package."), person("Justin",  "Talbot", role = "ctb", comment = "Code from the labeling package"), person("Joshua", "London", role = "ctb"))
# Depends: R (>= 3.3.0)
# Imports: ggplot2 (>= 3.0.0), graphics, grid, methods, purrr, scales, stringr, tibble
# Suggests: dplyr, covr, extrafont, glue, knitr, lattice, lintr, maps, mapproj, pander, rlang, rmarkdown, spelling, testthat, tidyr, vdiffr, withr
# Description: Some extra themes, geoms, and scales for 'ggplot2'. Provides 'ggplot2' themes and scales that replicate the look of plots by Edward Tufte, Stephen Few, 'Fivethirtyeight', 'The Economist', 'Stata', 'Excel', and 'The Wall Street Journal', among others. Provides 'geoms' for Tufte's box plot and range frame.
# License: GPL-2
# URL: http://github.com/jrnold/ggthemes
# BugReports: http://github.com/jrnold/ggthemes
# RoxygenNote: 6.1.1
# LazyData: true
# Language: en-US
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-04-09 14:41:14 UTC; jrnold
# Author: Jeffrey B. Arnold [aut, cre] (<https://orcid.org/0000-0001-9953-3904>), Gergely Daroczi [ctb], Bo Werth [ctb], Brian Weitzner [ctb], Joshua Kunst [ctb], Baptise Auguie [ctb], Bob Rudis [ctb], Hadley Wickham [ctb] (Code from the ggplot2 package.), Justin Talbot [ctb] (Code from the labeling package), Joshua London [ctb]
# Maintainer: Jeffrey B. Arnold <jeffrey.arnold@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-09 17:12:41 UTC
